// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tvXHwdOh0VykrP4Mg695JCk0Sz2eF-8',
    appId: '1:994411810016:web:8c7e5bf30bbc5f853ad485',
    messagingSenderId: '994411810016',
    projectId: 'instagramclone-8ced1',
    authDomain: 'instagramclone-8ced1.firebaseapp.com',
    storageBucket: 'instagramclone-8ced1.firebasestorage.app',
    measurementId: 'G-PT42J0YHW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwaMlXVegUD4bXP_6g1JS08PSsoSvwXkQ',
    appId: '1:994411810016:android:4432b1b97ceec2a23ad485',
    messagingSenderId: '994411810016',
    projectId: 'instagramclone-8ced1',
    storageBucket: 'instagramclone-8ced1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLahyhGNeh1XrVKhT0TxkDKgnvpGxXNkc',
    appId: '1:994411810016:ios:6e43bb18663c0c563ad485',
    messagingSenderId: '994411810016',
    projectId: 'instagramclone-8ced1',
    storageBucket: 'instagramclone-8ced1.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLahyhGNeh1XrVKhT0TxkDKgnvpGxXNkc',
    appId: '1:994411810016:ios:6e43bb18663c0c563ad485',
    messagingSenderId: '994411810016',
    projectId: 'instagramclone-8ced1',
    storageBucket: 'instagramclone-8ced1.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7tvXHwdOh0VykrP4Mg695JCk0Sz2eF-8',
    appId: '1:994411810016:web:f7429732237632303ad485',
    messagingSenderId: '994411810016',
    projectId: 'instagramclone-8ced1',
    authDomain: 'instagramclone-8ced1.firebaseapp.com',
    storageBucket: 'instagramclone-8ced1.firebasestorage.app',
    measurementId: 'G-1PCFC8T276',
  );
}
